doctrine:
    dbal:
        default_connection: livestream
        connections:
            livestream:
                driver: "pdo_mysql"
                host: "%env(DATABASE_HOST)%"
                port: "%env(DATABASE_PORT)%"
                dbname: "%env(DATABASE_NAME)%"
                user: "%env(DATABASE_USER)%"
                password: "%env(DATABASE_PASSWORD)%"
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: livestream
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
