jmose_command_scheduler:

    log_path: "%kernel.logs_dir%"
    send_ok: false

    excluded_command_namespaces:
        - _global
        - scheduler
        - server
        - container
        - config
        - generate
        - init
        - router
        - doctrine
        - debug
        - assets
        - security
        - translation
        - lint
        - cache
