security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            anonymous: ~
            http_basic: true
            provider: our_db_provider
            logout:
                success_handler: App\Controller\UserAuthenticationController
                path: /logout
                target: /

    access_control:
        - { path: /.*, roles: ROLE_USER }
