security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
#            pattern: ^/api(?!/doc$)
            pattern: ^/
            http_basic: true
            provider: our_db_provider
            logout:
                success_handler: App\Controller\UserAuthenticationController
                path: /logout
                target: /

    access_control:
    - { path: ^/admin, roles: ROLE_USER }
    - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

