security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#            pattern: ^/api(?!/doc$)
            pattern: ^/
            http_basic: true
            provider: our_db_provider
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    - { path: ^/api, roles: ROLE_USER }
    - { path: /api/doc, roles: ROLE_USER }
    - { path: ^/register, roles: ROLE_USER }
    - { path: /.*, roles: ROLE_USER }
    # - { path: ^/profile, roles: ROLE_USER }
