security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#            pattern: ^/api(?!/doc$)
            pattern: ^/
            http_basic: true
            provider: our_db_provider
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            logout:
                path: user_logout
                target: home_page
            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
#    - { path: ^/admin, roles: ROLE_USER }
#    - { path: /.*, roles: ROLE_USER }
