services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Twig\Validator:
        public: false
        tags:
        - { name: 'twig.extension' }

    App\Twig\Weekday:
        public: false
        tags:
        - { name: 'twig.extension' }
