framework:
    workflows:
        camera_stream:
            type: 'state_machine'
            supports:
            - App\Entity\Camera
            initial_place: inactive
            marking_store:
                type: 'single_state'
                arguments:
                - 'state'
            places:
            - inactive
            - starting
            - running
            - stopping
            - failure
            transitions:
                to_starting:
                    from: inactive
                    to: starting
                to_running:
                    from: starting
                    to: running
                to_stopping:
                    from: running
                    to: stopping
                to_inactive:
                    from: [stopping, failure]
                    to: inactive
                to_failure:
                    from: [starting, running, stopping, inactive]
                    to: failure
