version: '3'

services:
  web:
    ports:
    - 8080:80
  db:
    ports:
    - 3306:3306
  php:
    ports:
    - 9000:9000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: livestream-broadcaster-phpmyadmin
    ports:
    - 8081:80
    depends_on:
    - db
    environment:
    - PMA_USER=${DATABASE_USER}
    - PMA_PASSWORD=${DATABASE_PASSWORD}
