version: '3'

services:
  php:
    build:
      context: docker-build/php
      dockerfile: Dockerfile
      args:
        LIVESTREAM_USER: ${LIVESTREAM_USER}
    container_name: livestream-php
    depends_on:
    - db
    volumes:
    - ./:/var/www/livestream:cached
    - ./var/log:/var/log
    command: ["php-fpm"]
  web:
    build: docker-build/nginx
    container_name: livestream-nginx
    restart: always
    ports:
    - 8080:80
    depends_on:
    - php
    - db
    volumes:
    - ./:/var/www/livestream:cached
    - ./var/log:/var/log/nginx
  db:
    image: mysql/mysql-server:5.7
    container_name: livestream-mysql
    env_file:
      - .env
    environment:
    - MYSQL_DATABASE=${DATABASE_NAME}
    - MYSQL_USER=${DATABASE_USER}
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
    - database:/var/lib/mysql
  yarn:
    build:
      context: docker-build/yarn
      dockerfile: Dockerfile
    container_name: livestream-yarn
    volumes:
    - ./:/usr/src/app
    tty: true
  supervisor:
    build:
      context: docker-build/php
      dockerfile: Dockerfile
      args:
        LIVESTREAM_USER: ${LIVESTREAM_USER}
    container_name: livestream-supervisor
    depends_on:
      - php
    volumes:
      - ./:/var/www/livestream:cached
      - ./var/log:/var/log
      - ./docker-build/supervisor/conf/supervisord.conf:/etc/supervisor/supervisord.conf
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

volumes:
  database:
