scheduler_list:
  path: /list
  defaults: { _controller: App\Controller\ScheduleController:list }
  methods: [GET]

schedule_create_recurring:
  path: /details/create-recurring
  defaults: { _controller: App\Controller\ScheduleController:createRecurringSchedule }
  methods: [GET, POST]

schedule_create_onetime:
  path: /details/create-onetime
  defaults: { _controller: App\Controller\ScheduleController:createOnetimeSchedule }
  methods: [GET, POST]

schedule_edit:
  path: /details/edit-stream/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:editSchedule }
  methods: [GET, POST]

schedule_toggle_disabling:
  path: /details/disable/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:toggleDisablingSchedule }
  methods: [GET]

schedule_execution:
  path: /details/execution/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:executeScheduleWithNextExecution }
  methods: [GET]

schedule_remove:
  path: /details/remove/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:removeSchedule }
  methods: [GET]

schedule_unwreck:
  path: /details/unwreck/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:unwreckSchedule }
  methods: [GET]

schedule_view_logging:
  defaults: { _controller: App\Controller\ScheduleLogBookController:viewLogging }
  path: /details/logging/{scheduleId}
  methods: [GET]
