scheduler_list:
  path:
    en: /list
    nl: /lijst
  defaults: { _controller: App\Controller\ScheduleController:list }
  methods: [GET]

schedule_create_recurring:
  path:
    en: /details/create-recurring
    nl: /details/voeg-terugkerende-toe
  defaults: { _controller: App\Controller\ScheduleController:createRecurringSchedule }
  methods: [GET, POST]

schedule_create_onetime:
  path:
    en: /details/create-onetime
    nl: /details/voeg-eenmalige-toe
  defaults: { _controller: App\Controller\ScheduleController:createOnetimeSchedule }
  methods: [GET, POST]

schedule_edit:
  path:
    en: /details/edit-stream/{scheduleId}
    nl: /details/wijzig-stream/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:editSchedule }
  methods: [GET, POST]

schedule_toggle_disabling:
  path: /details/disable/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:toggleDisablingSchedule }
  methods: [GET]

schedule_remove:
  path: /details/remove/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:removeSchedule }
  methods: [GET]

schedule_unwreck:
  path: /details/unwreck/{scheduleId}
  defaults: { _controller: App\Controller\ManageScheduleController:unwreckSchedule }
  methods: [GET]

schedule_view_logging:
  defaults: { _controller: App\Controller\ScheduleLogBookController:viewLogging }
  path:
    en: /details/logbook/{scheduleId}
    nl: /details/logboek/{scheduleId}
  methods: [GET]
