user_list:
  path: /users
  defaults: { _controller: App\Controller\UserManagementController:usersList }
  methods: [GET]

user_details:
  path: /details/{userId}
  defaults: { _controller: App\Controller\UserManagementController:userDetails }
  methods: [GET, POST]

user_toggle_disabling:
  path: /users/disable/{userId}
  defaults: { _controller: App\Controller\UserManagementController:toggleDisablingUser }
  methods: [GET]

user_delete:
  path: /users/delete/{userId}
  defaults: { _controller: App\Controller\UserManagementController:deleteUser }
  methods: [GET]

user_registration:
  path:
    en: /registration
    nl: /registratie
  defaults: { _controller: FOSUserBundle:Registration:register }
  methods: [GET, POST]

fos_user_registration_confirmed:
  path: /admin/users
  defaults: { _controller: App\Controller\UserManagementController:usersList }
  methods: [GET]
