api:
  prefix: /api/v1
  resource: "routes/routes_api.yaml"

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
  prefix: /{_locale}/admin
  resource: "routes/admin.yaml"
  defaults:   { _locale: '%locale%' }
  requirements:
    _locale: '%app.locales%'

manual_page:
  path: /manual
  defaults: { _controller: App\Controller\ManualController:manualPage }
  methods: [GET]

home_page:
  path: /
  defaults: { _controller: fos_user.security.controller:loginAction }
  methods: [GET]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
