api:
  prefix: /api/v1
  resource: "routes/routes_api.yaml"

admin_page:
  path: /admin
  defaults: { _controller: App\Controller\HomepageController:admin }
  methods: [GET]

registration:
  path: /admin/registration
  defaults: { _controller: App\Controller\RegistrationController:register }
  methods: [GET, POST]

user_list:
  path: /admin/users
  defaults: { _controller: App\Controller\UserManagementController:usersList }
  methods: [GET]

user_details:
  path: /admin/details/{userId}
  defaults: { _controller: App\Controller\UserManagementController:userDetails }
  methods: [GET, POST]

user_toggle_disabling:
  path: /admin/users/disable/{userId}
  defaults: { _controller: App\Controller\UserManagementController:toggleDisablingUser }
  methods: [GET]

user_delete:
  path: /admin/users/delete/{userId}
  defaults: { _controller: App\Controller\UserManagementController:deleteUser }
  methods: [GET]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
