api:
  prefix: /api/v1
  resource: "routes_api.yaml"

registration:
  path: /register
  defaults: { _controller: App\Controller\RegistrationController:register }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
