api:
  prefix: /api/v1
  resource: "routes/routes_api.yaml"

user:
  prefix: /
  resource: "routes/user.yaml"

scheduler:
  prefix: /admin/schedule/
  resource: "routes/scheduler.yaml"

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

home_page:
  path: /
  defaults: { _controller: App\Controller\HomepageController:home }
  methods: [GET]

admin_page:
  path: /admin
  defaults: { _controller: App\Controller\HomepageController:admin }
  methods: [GET]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

start_stream:
  path: /admin/stream/start
  defaults: { _controller: App\Controller\LivestreamController:startStream }
  methods: [GET]

stop_stream:
  path: /admin/stream/stop
  defaults: { _controller: App\Controller\LivestreamController:stopStream }
  methods: [GET]

camera_configuration_list:
  path: /admin/configuration
  defaults: { _controller: App\Controller\CameraConfigurationController:configurationList }
