api:
  prefix: /api/v1
  resource: "routes/routes_api.yaml"

logout:
  path: /logout

home_page:
  path: /
  defaults: { _controller: App\Controller\CameraConfigurationController:configurationList }
  methods: [GET]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

camera_configuration_list:
  path: /account/configuration
  defaults: { _controller: App\Controller\CameraConfigurationController:configurationList }

channel_list:
  path: /account/channel/list
  defaults: { _controller: App\Controller\ChannelController:channelList }
  methods: [GET]

channel_create:
  path: /account/channel/create
  defaults: { _controller: App\Controller\ChannelController:editChannel }
  methods: [GET|POST]

