parameters:
    app.locales: 'en|nl'
    locale: 'en'
    mailer_user: 'pvuyky@gmail.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    FOS\UserBundle\Controller\RegistrationController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
